"""Assemble a personalised recap quiz from one user's stored checks.

Questions are built locally from SQLite rather than generated by a model: the
recap has to be reproducible, has to work when the OpenAI key is unavailable,
and must never invent a verdict the user was not actually shown. Every question
is validated against the limits Telegram enforces on quiz polls before it can
leave this module.
"""

import random
from dataclasses import dataclass
from typing import Sequence

from app.literacy import (
    GENERAL_BANK,
    TECHNIQUE_TIPS,
    BankQuestion,
    Technique,
    bank_questions_for,
)
from app.storage import StoredCheck
from app.verdict import Verdict

# Limits from https://core.telegram.org/bots/api#sendpoll
MAX_QUESTION_LENGTH = 300
MAX_OPTION_LENGTH = 100
MAX_OPTIONS = 12
MIN_OPTIONS = 2
MAX_EXPLANATION_LENGTH = 200

DEFAULT_QUESTION_COUNT = 5
MAX_PERSONAL_QUESTIONS = 3
CLAIM_SNIPPET_LENGTH = 170

ORIGIN_PERSONAL = "personal"
ORIGIN_TARGETED = "targeted"
ORIGIN_GENERAL = "general"

VERDICT_OPTIONS: dict[Verdict, str] = {
    Verdict.TRUE: "True - trusted sources support it",
    Verdict.FALSE: "False - trusted sources contradict it",
    Verdict.MISLEADING: "Misleading - partly true but framed to mislead",
    Verdict.SATIRE: "Satire - written as comedy, not as news",
    Verdict.UNVERIFIED: "Unverified - no trusted source could confirm it",
}


@dataclass(frozen=True)
class QuizQuestion:
    """One question, already shaped for Telegram's quiz poll."""

    question: str
    options: tuple[str, ...]
    correct_option_id: int
    explanation: str
    technique: Technique
    origin: str
    check_id: int | None = None

    def __post_init__(self) -> None:
        if not 1 <= len(self.question) <= MAX_QUESTION_LENGTH:
            raise ValueError(
                f"A quiz question must be 1-{MAX_QUESTION_LENGTH} characters."
            )
        if not MIN_OPTIONS <= len(self.options) <= MAX_OPTIONS:
            raise ValueError(
                f"A quiz needs {MIN_OPTIONS}-{MAX_OPTIONS} answer options."
            )
        if len(set(self.options)) != len(self.options):
            raise ValueError("Quiz options must be distinct.")
        for option in self.options:
            if not 1 <= len(option) <= MAX_OPTION_LENGTH:
                raise ValueError(
                    f"Each quiz option must be 1-{MAX_OPTION_LENGTH} characters."
                )
        if not 0 <= self.correct_option_id < len(self.options):
            raise ValueError("The correct option must be one of the options.")
        if len(self.explanation) > MAX_EXPLANATION_LENGTH:
            raise ValueError(
                f"A quiz explanation must be at most {MAX_EXPLANATION_LENGTH} characters."
            )

    @property
    def correct_option(self) -> str:
        return self.options[self.correct_option_id]


@dataclass(frozen=True)
class Quiz:
    """The full set of questions for one /quiz run."""

    questions: tuple[QuizQuestion, ...]

    def __len__(self) -> int:
        return len(self.questions)

    @property
    def personal_count(self) -> int:
        return sum(1 for item in self.questions if item.origin == ORIGIN_PERSONAL)

    @property
    def is_personalised(self) -> bool:
        return any(item.origin != ORIGIN_GENERAL for item in self.questions)


def build_quiz(
    checks: Sequence[StoredCheck] = (),
    technique_counts: dict[str, int] | None = None,
    question_count: int = DEFAULT_QUESTION_COUNT,
    rng: random.Random | None = None,
) -> Quiz:
    """Build a recap: the user's own checks first, then targeted technique drills."""
    rng = rng or random.Random()
    technique_counts = technique_counts or {}
    question_count = max(1, min(question_count, len(GENERAL_BANK) + MAX_PERSONAL_QUESTIONS))

    # Keep room for technique drills in a normal five-question recap, but never
    # drop the user's own history entirely from a short one.
    personal_allowance = min(MAX_PERSONAL_QUESTIONS, max(1, question_count - 2))
    questions: list[QuizQuestion] = []
    for check in _usable_checks(checks):
        if len(questions) >= personal_allowance:
            break
        question = _verdict_recall_question(check, rng)
        if question is not None:
            questions.append(question)

    used_bank: set[str] = set()
    for bank_question in _bank_order(technique_counts, rng):
        if len(questions) >= question_count:
            break
        if bank_question.question in used_bank:
            continue
        used_bank.add(bank_question.question)
        origin = (
            ORIGIN_TARGETED
            if bank_question.technique.value in technique_counts
            else ORIGIN_GENERAL
        )
        questions.append(_from_bank(bank_question, origin, rng))

    return Quiz(questions=tuple(questions[:question_count]))


def _usable_checks(checks: Sequence[StoredCheck]) -> list[StoredCheck]:
    """Keep checks that carry a real verdict and enough text to quote back."""
    usable = []
    seen: set[str] = set()
    for check in checks:
        verdict = _verdict_of(check)
        if verdict is None:
            continue
        snippet = _snippet(check.input_text)
        if len(snippet) < 12 or snippet.lower() in seen:
            continue
        seen.add(snippet.lower())
        usable.append(check)
    return usable


def _verdict_of(check: StoredCheck) -> Verdict | None:
    try:
        return Verdict(check.verdict) if check.verdict else None
    except ValueError:
        return None


def _verdict_recall_question(
    check: StoredCheck, rng: random.Random
) -> QuizQuestion | None:
    """Ask the user to recall the verdict on something they forwarded in."""
    verdict = _verdict_of(check)
    if verdict is None:
        return None

    day = check.local_day.strftime("%d %b")
    question = (
        f"On {day} you asked TrustLens about this: "
        f'"{_snippet(check.input_text)}" What was the verdict?'
    )
    if len(question) > MAX_QUESTION_LENGTH:
        return None

    distractors = [item for item in Verdict if item is not verdict]
    rng.shuffle(distractors)
    chosen = [verdict, *distractors[:3]]
    rng.shuffle(chosen)
    options = tuple(VERDICT_OPTIONS[item] for item in chosen)

    technique = _technique_of(check)
    explanation = _explanation_for(check, technique)
    return QuizQuestion(
        question=question,
        options=options,
        correct_option_id=chosen.index(verdict),
        explanation=explanation,
        technique=technique,
        origin=ORIGIN_PERSONAL,
        check_id=check.id,
    )


def _technique_of(check: StoredCheck) -> Technique:
    try:
        return Technique(check.technique) if check.technique else Technique.MISSING_SOURCE
    except ValueError:
        return Technique.MISSING_SOURCE


def _explanation_for(check: StoredCheck, technique: Technique) -> str:
    """Reuse the explanation the user was given, falling back to the tip."""
    explanation = _collapse(check.explanation or "")
    if len(explanation) < 20:
        explanation = TECHNIQUE_TIPS[technique]
    return _truncate(explanation, MAX_EXPLANATION_LENGTH)


def _bank_order(
    technique_counts: dict[str, int], rng: random.Random
) -> list[BankQuestion]:
    """Order the bank so the techniques a user actually met come first."""
    ranked = sorted(
        technique_counts.items(), key=lambda item: (-item[1], item[0])
    )
    ordered: list[BankQuestion] = []
    for name, _count in ranked:
        try:
            technique = Technique(name)
        except ValueError:
            continue
        ordered.extend(bank_questions_for(technique))

    remainder = [item for item in GENERAL_BANK if item not in ordered]
    rng.shuffle(remainder)
    return ordered + remainder


def _from_bank(
    bank_question: BankQuestion, origin: str, rng: random.Random
) -> QuizQuestion:
    """Shuffle a curated question's options so the answer is never in one place."""
    options = list(bank_question.options)
    rng.shuffle(options)
    return QuizQuestion(
        question=bank_question.question,
        options=tuple(options),
        correct_option_id=options.index(bank_question.correct_option),
        explanation=_truncate(bank_question.explanation, MAX_EXPLANATION_LENGTH),
        technique=bank_question.technique,
        origin=origin,
    )


def _snippet(text: str, limit: int = CLAIM_SNIPPET_LENGTH) -> str:
    return _truncate(_collapse(text), limit)


def _collapse(text: str) -> str:
    """Flatten whitespace: poll text has no room for line breaks."""
    return " ".join(text.split()).replace('"', "'")


def _truncate(text: str, limit: int) -> str:
    """Cut on a word boundary where possible and mark the cut with an ellipsis."""
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rstrip()
    space = cut.rfind(" ")
    if space > limit // 2:
        cut = cut[:space]
    return f"{cut.rstrip(' .,;:')}…"
